#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 30 15:13:11 PDT 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_pipeline_behav -key {Behavioral:sim_1:Functional:test_pipeline} -tclbatch test_pipeline.tcl -view /media/danny/exSSD/schoolfiles/school_files/cpe333/lab3_basic_pipeline/basic_pipeline/test_pipeline_behav1.wcfg -log simulate.log"
xsim test_pipeline_behav -key {Behavioral:sim_1:Functional:test_pipeline} -tclbatch test_pipeline.tcl -view /media/danny/exSSD/schoolfiles/school_files/cpe333/lab3_basic_pipeline/basic_pipeline/test_pipeline_behav1.wcfg -log simulate.log

