@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Oct 02 19:12:12 -0700 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim OTTERSim_behav -key {Behavioral:sim_1:Functional:OTTERSim} -tclbatch OTTERSim.tcl -view Z:/schoolfiles/school_files/cpe333/Lab0_1_performance/lab0_1/OTTERSim_behav.wcfg -log simulate.log"
call xsim  OTTERSim_behav -key {Behavioral:sim_1:Functional:OTTERSim} -tclbatch OTTERSim.tcl -view Z:/schoolfiles/school_files/cpe333/Lab0_1_performance/lab0_1/OTTERSim_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
